### ISSUE TITLE
Not working "access token provided is invalid"

### ISSUE THREAD

**Issue by mahadevan** [gavvvr/obsidian-imgur-plugin#21] opened 2022-01-11 07:16 UTC
When I try to drag an image into obsidian it shows 👇

`Upload failed, remote server returned an error: The access token provided is invalid.`

Tried connecting my imgur account again, it is showing connected successfully, but again when I try it is showing the same error message.

Anonymous uploads works. But I need to upload it to my imgur account.

**Comment by gavvvr** [comment] 2022-01-18 22:57
Hi @mahadevan
I can not reproduce your problem. I've checked both: anonymous and authenticated uploads.
Please check once again if the problem is present.

PS: Also I do not understand how did you get the plugin working 8 days ago, because it was broken during last month (see #20)

**Comment by mahadevan** [comment] 2022-01-19 05:04
> Hi @mahadevan I can not reproduce your problem. I've checked both: anonymous and authenticated uploads. Please check once again if the problem is present.
> 
> PS: Also I do not understand how did you get the plugin working 8 days ago, because it was broken during last month (see #20)

It was a "Live-Preview" compatability issue. Now with the new plugin update, it is resolved & now working 👍🏼. Thanks.

**Comment by gavvvr** [comment] 2022-01-19 09:30
Good to hear it's resolved! But I am still not sure it was related to live preview issue. To me the plugin was simply deactivated with Live Preview. But you reported an error _as if_ the plugin actually tried to upload anything. Do not understand how this could happen. Anyway, closing this one as the problem no longer exists.

**Closed by gavvvr** 2022-01-19 09:30 UTC
